#ifndef ZENON_PROVIDER_ATTESTOR_PKCS11_MINIMAL_H
#define ZENON_PROVIDER_ATTESTOR_PKCS11_MINIMAL_H

#include <stddef.h>
#include <stdint.h>

typedef uint8_t CK_BYTE;
typedef CK_BYTE *CK_BYTE_PTR;
typedef uint8_t CK_BBOOL;
typedef unsigned long CK_ULONG;
typedef CK_ULONG *CK_ULONG_PTR;
typedef CK_ULONG CK_RV;
typedef CK_ULONG CK_SLOT_ID;
typedef CK_SLOT_ID *CK_SLOT_ID_PTR;
typedef CK_ULONG CK_SESSION_HANDLE;
typedef CK_ULONG CK_OBJECT_HANDLE;
typedef CK_ULONG CK_OBJECT_CLASS;
typedef CK_ULONG CK_KEY_TYPE;
typedef CK_ULONG CK_FLAGS;
typedef CK_ULONG CK_USER_TYPE;
typedef CK_ULONG CK_MECHANISM_TYPE;
typedef CK_ULONG CK_ATTRIBUTE_TYPE;
typedef void *CK_VOID_PTR;
typedef char CK_CHAR;
typedef CK_CHAR *CK_CHAR_PTR;
typedef uint8_t CK_UTF8CHAR;
typedef CK_UTF8CHAR *CK_UTF8CHAR_PTR;

#define CK_TRUE ((CK_BBOOL)1)
#define CK_FALSE ((CK_BBOOL)0)
#define CK_INVALID_HANDLE ((CK_ULONG)0)

#define CKR_OK ((CK_RV)0x00000000UL)
#define CKR_ARGUMENTS_BAD ((CK_RV)0x00000007UL)
#define CKR_BUFFER_TOO_SMALL ((CK_RV)0x00000150UL)
#define CKR_CRYPTOKI_NOT_INITIALIZED ((CK_RV)0x00000190UL)
#define CKR_FUNCTION_NOT_SUPPORTED ((CK_RV)0x00000054UL)
#define CKR_MECHANISM_INVALID ((CK_RV)0x00000070UL)
#define CKR_OBJECT_HANDLE_INVALID ((CK_RV)0x00000082UL)
#define CKR_PIN_INCORRECT ((CK_RV)0x000000A0UL)
#define CKR_SESSION_HANDLE_INVALID ((CK_RV)0x000000B3UL)
#define CKR_USER_NOT_LOGGED_IN ((CK_RV)0x00000101UL)

#define CKF_RW_SESSION ((CK_FLAGS)0x00000002UL)
#define CKF_SERIAL_SESSION ((CK_FLAGS)0x00000004UL)

#define CKU_SO ((CK_USER_TYPE)0UL)
#define CKU_USER ((CK_USER_TYPE)1UL)

#define CKO_PUBLIC_KEY ((CK_OBJECT_CLASS)0x00000002UL)
#define CKO_PRIVATE_KEY ((CK_OBJECT_CLASS)0x00000003UL)
#define CKK_EC_EDWARDS ((CK_KEY_TYPE)0x00000040UL)

#define CKA_CLASS ((CK_ATTRIBUTE_TYPE)0x00000000UL)
#define CKA_TOKEN ((CK_ATTRIBUTE_TYPE)0x00000001UL)
#define CKA_PRIVATE ((CK_ATTRIBUTE_TYPE)0x00000002UL)
#define CKA_LABEL ((CK_ATTRIBUTE_TYPE)0x00000003UL)
#define CKA_VALUE ((CK_ATTRIBUTE_TYPE)0x00000011UL)
#define CKA_KEY_TYPE ((CK_ATTRIBUTE_TYPE)0x00000100UL)
#define CKA_ID ((CK_ATTRIBUTE_TYPE)0x00000102UL)
#define CKA_SIGN ((CK_ATTRIBUTE_TYPE)0x00000108UL)
#define CKA_VERIFY ((CK_ATTRIBUTE_TYPE)0x0000010AUL)
#define CKA_EC_PARAMS ((CK_ATTRIBUTE_TYPE)0x00000180UL)
#define CKA_EC_POINT ((CK_ATTRIBUTE_TYPE)0x00000181UL)

#define CKM_EC_EDWARDS_KEY_PAIR_GEN ((CK_MECHANISM_TYPE)0x00001055UL)
#define CKM_EDDSA ((CK_MECHANISM_TYPE)0x00001057UL)

typedef struct CK_VERSION {
  CK_BYTE major;
  CK_BYTE minor;
} CK_VERSION;

typedef struct CK_TOKEN_INFO {
  CK_UTF8CHAR label[32];
  CK_UTF8CHAR manufacturerID[32];
  CK_UTF8CHAR model[16];
  CK_CHAR serialNumber[16];
  CK_FLAGS flags;
  CK_ULONG ulMaxSessionCount;
  CK_ULONG ulSessionCount;
  CK_ULONG ulMaxRwSessionCount;
  CK_ULONG ulRwSessionCount;
  CK_ULONG ulMaxPinLen;
  CK_ULONG ulMinPinLen;
  CK_ULONG ulTotalPublicMemory;
  CK_ULONG ulFreePublicMemory;
  CK_ULONG ulTotalPrivateMemory;
  CK_ULONG ulFreePrivateMemory;
  CK_VERSION hardwareVersion;
  CK_VERSION firmwareVersion;
  CK_CHAR utcTime[16];
} CK_TOKEN_INFO;

typedef CK_TOKEN_INFO *CK_TOKEN_INFO_PTR;

typedef struct CK_SESSION_INFO {
  CK_SLOT_ID slotID;
  CK_ULONG state;
  CK_FLAGS flags;
  CK_ULONG ulDeviceError;
} CK_SESSION_INFO;

typedef CK_SESSION_INFO *CK_SESSION_INFO_PTR;

typedef struct CK_MECHANISM {
  CK_MECHANISM_TYPE mechanism;
  CK_VOID_PTR pParameter;
  CK_ULONG ulParameterLen;
} CK_MECHANISM;

typedef CK_MECHANISM *CK_MECHANISM_PTR;

typedef struct CK_ATTRIBUTE {
  CK_ATTRIBUTE_TYPE type;
  CK_VOID_PTR pValue;
  CK_ULONG ulValueLen;
} CK_ATTRIBUTE;

typedef CK_ATTRIBUTE *CK_ATTRIBUTE_PTR;

typedef struct CK_FUNCTION_LIST CK_FUNCTION_LIST;
typedef CK_FUNCTION_LIST *CK_FUNCTION_LIST_PTR;
typedef CK_FUNCTION_LIST_PTR *CK_FUNCTION_LIST_PTR_PTR;

struct CK_FUNCTION_LIST {
  CK_VERSION version;
  CK_RV (*C_Initialize)(CK_VOID_PTR);
  CK_RV (*C_Finalize)(CK_VOID_PTR);
  CK_RV (*C_GetInfo)(CK_VOID_PTR);
  CK_RV (*C_GetFunctionList)(CK_FUNCTION_LIST_PTR_PTR);
  CK_RV (*C_GetSlotList)(CK_BBOOL, CK_SLOT_ID_PTR, CK_ULONG_PTR);
  CK_RV (*C_GetSlotInfo)(CK_SLOT_ID, CK_VOID_PTR);
  CK_RV (*C_GetTokenInfo)(CK_SLOT_ID, CK_TOKEN_INFO_PTR);
  CK_RV (*C_GetMechanismList)(CK_SLOT_ID, CK_MECHANISM_TYPE *, CK_ULONG_PTR);
  CK_RV (*C_GetMechanismInfo)(CK_SLOT_ID, CK_MECHANISM_TYPE, CK_VOID_PTR);
  CK_RV (*C_InitToken)(CK_SLOT_ID, CK_UTF8CHAR_PTR, CK_ULONG, CK_UTF8CHAR_PTR);
  CK_RV (*C_InitPIN)(CK_SESSION_HANDLE, CK_UTF8CHAR_PTR, CK_ULONG);
  CK_RV (*C_SetPIN)(CK_SESSION_HANDLE, CK_UTF8CHAR_PTR, CK_ULONG, CK_UTF8CHAR_PTR, CK_ULONG);
  CK_RV (*C_OpenSession)(CK_SLOT_ID, CK_FLAGS, CK_VOID_PTR, CK_VOID_PTR, CK_SESSION_HANDLE *);
  CK_RV (*C_CloseSession)(CK_SESSION_HANDLE);
  CK_RV (*C_CloseAllSessions)(CK_SLOT_ID);
  CK_RV (*C_GetSessionInfo)(CK_SESSION_HANDLE, CK_SESSION_INFO_PTR);
  CK_RV (*C_GetOperationState)(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG_PTR);
  CK_RV (*C_SetOperationState)(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_OBJECT_HANDLE, CK_OBJECT_HANDLE);
  CK_RV (*C_Login)(CK_SESSION_HANDLE, CK_USER_TYPE, CK_UTF8CHAR_PTR, CK_ULONG);
  CK_RV (*C_Logout)(CK_SESSION_HANDLE);
  CK_RV (*C_CreateObject)(CK_SESSION_HANDLE, CK_ATTRIBUTE_PTR, CK_ULONG, CK_OBJECT_HANDLE *);
  CK_RV (*C_CopyObject)(CK_SESSION_HANDLE, CK_OBJECT_HANDLE, CK_ATTRIBUTE_PTR, CK_ULONG, CK_OBJECT_HANDLE *);
  CK_RV (*C_DestroyObject)(CK_SESSION_HANDLE, CK_OBJECT_HANDLE);
  CK_RV (*C_GetObjectSize)(CK_SESSION_HANDLE, CK_OBJECT_HANDLE, CK_ULONG_PTR);
  CK_RV (*C_GetAttributeValue)(CK_SESSION_HANDLE, CK_OBJECT_HANDLE, CK_ATTRIBUTE_PTR, CK_ULONG);
  CK_RV (*C_SetAttributeValue)(CK_SESSION_HANDLE, CK_OBJECT_HANDLE, CK_ATTRIBUTE_PTR, CK_ULONG);
  CK_RV (*C_FindObjectsInit)(CK_SESSION_HANDLE, CK_ATTRIBUTE_PTR, CK_ULONG);
  CK_RV (*C_FindObjects)(CK_SESSION_HANDLE, CK_OBJECT_HANDLE *, CK_ULONG, CK_ULONG_PTR);
  CK_RV (*C_FindObjectsFinal)(CK_SESSION_HANDLE);
  CK_RV (*C_EncryptInit)(CK_SESSION_HANDLE, CK_MECHANISM_PTR, CK_OBJECT_HANDLE);
  CK_RV (*C_Encrypt)(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_BYTE_PTR, CK_ULONG_PTR);
  CK_RV (*C_EncryptUpdate)(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_BYTE_PTR, CK_ULONG_PTR);
  CK_RV (*C_EncryptFinal)(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG_PTR);
  CK_RV (*C_DecryptInit)(CK_SESSION_HANDLE, CK_MECHANISM_PTR, CK_OBJECT_HANDLE);
  CK_RV (*C_Decrypt)(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_BYTE_PTR, CK_ULONG_PTR);
  CK_RV (*C_DecryptUpdate)(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_BYTE_PTR, CK_ULONG_PTR);
  CK_RV (*C_DecryptFinal)(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG_PTR);
  CK_RV (*C_DigestInit)(CK_SESSION_HANDLE, CK_MECHANISM_PTR);
  CK_RV (*C_Digest)(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_BYTE_PTR, CK_ULONG_PTR);
  CK_RV (*C_DigestUpdate)(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG);
  CK_RV (*C_DigestKey)(CK_SESSION_HANDLE, CK_OBJECT_HANDLE);
  CK_RV (*C_DigestFinal)(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG_PTR);
  CK_RV (*C_SignInit)(CK_SESSION_HANDLE, CK_MECHANISM_PTR, CK_OBJECT_HANDLE);
  CK_RV (*C_Sign)(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_BYTE_PTR, CK_ULONG_PTR);
  CK_RV (*C_SignUpdate)(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG);
  CK_RV (*C_SignFinal)(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG_PTR);
  CK_RV (*C_SignRecoverInit)(CK_SESSION_HANDLE, CK_MECHANISM_PTR, CK_OBJECT_HANDLE);
  CK_RV (*C_SignRecover)(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_BYTE_PTR, CK_ULONG_PTR);
  CK_RV (*C_VerifyInit)(CK_SESSION_HANDLE, CK_MECHANISM_PTR, CK_OBJECT_HANDLE);
  CK_RV (*C_Verify)(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_BYTE_PTR, CK_ULONG);
  CK_RV (*C_VerifyUpdate)(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG);
  CK_RV (*C_VerifyFinal)(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG);
  CK_RV (*C_VerifyRecoverInit)(CK_SESSION_HANDLE, CK_MECHANISM_PTR, CK_OBJECT_HANDLE);
  CK_RV (*C_VerifyRecover)(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_BYTE_PTR, CK_ULONG_PTR);
  CK_RV (*C_DigestEncryptUpdate)(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_BYTE_PTR, CK_ULONG_PTR);
  CK_RV (*C_DecryptDigestUpdate)(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_BYTE_PTR, CK_ULONG_PTR);
  CK_RV (*C_SignEncryptUpdate)(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_BYTE_PTR, CK_ULONG_PTR);
  CK_RV (*C_DecryptVerifyUpdate)(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_BYTE_PTR, CK_ULONG_PTR);
  CK_RV (*C_GenerateKey)(CK_SESSION_HANDLE, CK_MECHANISM_PTR, CK_ATTRIBUTE_PTR, CK_ULONG, CK_OBJECT_HANDLE *);
  CK_RV (*C_GenerateKeyPair)(CK_SESSION_HANDLE, CK_MECHANISM_PTR, CK_ATTRIBUTE_PTR, CK_ULONG, CK_ATTRIBUTE_PTR, CK_ULONG, CK_OBJECT_HANDLE *, CK_OBJECT_HANDLE *);
};

typedef CK_RV (*CK_C_GetFunctionList)(CK_FUNCTION_LIST_PTR_PTR);

#endif
